name: cd
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKER_USER: amaldevc
      DOCKER_PASS_TOKEN: ${{ secrets.DOCKER_PASS_TOKEN }}
    steps:
      - name: docker login
        run: sudo docker login -u $DOCKER_USER -p $DOCKER_PASS_TOKEN
      - name: install app
        run: sudo docker pull $DOCKER_USER/fire_ext_model:latest
      - name: run app
        run: sudo docker run -d -p 8002:8002 --name fire_ext_model $DOCKER_USER/fire_ext_model
      - name: docker logout
        run: sudo docker logout
